name: cisl-cloud-base
channels:
  - conda-forge
dependencies:
  - argopy
  - beautifulsoup4
  - bokeh
  - boto3
  - bottleneck
  - ca-certificates
  - cartopy 
  - cdsapi
  - celluloid
  - cfgrib
  - cf-units
  - click
  - cmocean
  - dask
  - dask-gateway
  - dask-jobqueue
  - datashader
  - descartes
  - docopt
  - earthaccess
  - erddapy
  - esmpy
  - flox
  - fiona
  - gdal
  - geocat-comp
  - geocat-viz
  - geocube
  - geopandas
  - geopy
  - geoviews-core
  - ghp-import
  - globus-cli
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ipykernel>=6.21.2
  - ipympl
  - ipywidgets
  - ipywidgets-bokeh
  - jupyterhub
  - jupyterlab==3.6.3
  - jupyter_bokeh
  - jupyter-panel-proxy
  - jupyter-resource-usage
  - ldcpy
  - matplotlib
  - metpy
  - mpi4py
  - nb_conda_kernels
  - nbstripout
  - nc-time-axis
  - netcdf4
  - nodejs>=18.0
  - notebook
  - numba
  - numcodecs
  - numexpr
  - numpy
  - ocgis
  - pandas
  - panel
  - papermill
  - pillow
  - pop-tools
  - pydap
  - pygrib
  - pyhdf
  - pylint
  - pynco
  - pyngl
  - pystac
  - pystac-client
  - pytables
  - pyqt
  - pyspharm
  - pytables
  - python=3.10
  - python-awips
  - python-graphviz
  - python-wget
  - rasterio
  - rechunker
  - rio-cogeo
  - rioxarray
  - satpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - shapely
  - statsmodels
  - stackstac
  - tobac
  - widgetsnbextension
  - windspharm
  - wrf-python
  - xarray
  - xesmf
  - xgcm
  - xrft
  - zarr