channels:
  - conda-forge
dependencies:
  - cartopy
  - dask-gateway
  - dask-jobqueue
  - ipywidgets
  - jupyter
  - jupyter-server-proxy
  - matplotlib
  - metpy
  - pip
  - python>=3.6,<3.8
  - python-awips
  - python-graphviz
  - siphon
  - xarray