# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CISL Cloud Pilot
author: The CISL Cloud Pilot Team
logo: images/NSF-NCAR.png
email: "cisl-cloud-pilot@ucar.edu"
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns:
    - '*rda-local*'
    - '*rda-remote*'
    - '*create-jb*'
    - '*stratus-cmd*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

#######################################################################################
# Launch button settings

sphinx:
  config:
    html_favicon: images/favicon.ico
    html_last_updated_fmt: '%-d %B %Y'
    html_theme: sphinx_pythia_theme
    html_theme_options:
      home_page_in_toc: false
      repository_url: https://github.com/NCAR/cisl-cloud # Online location of your book
      repository_branch: main
      navbar_align: content
      use_issues_button: true
      use_repository_button: true
      launch_buttons:
        notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
        #binderhub_url: "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org) won't work with private repo
        jupyterhub_url: "https://jupyter.k8s.ucar.edu/"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu) won't work with private repo
      extra_navbar: |
        <p style="font-weight: 700;text-decoration: underline;color: red;">This site is currently in active development.</p>
        Follow our <a href="https://jira.ucar.edu/secure/RapidBoard.jspa?rapidView=220&projectKey=CCPP">Kanban board</a><br>
        Visit our <a href="https://github.com/NCAR/cisl-cloud">GitHub Repo</a><br>
        <a href="https://github.com/NicholasCote/jupyterbook-cisl-theme">Copy this JupyterBook layout</a><hr>
        <div>Powered by <a href="https://jupyterbook.org">Jupyter Book</a></div><br>
        Theme by <a href="https://projectpythia.org/">Project Pythia</a>
      navbar_links:
        - name: Cloud Docs
          url: main
        - name: Resources
          url: overview/services
          dropdown: true 
          dropdown_links:
          - name: 'Harbor - Container Registry'
            url: https://hub.k8s.ucar.edu/
          - name: Stratus Object Storage
            url: https://stratus-admin.ucar.edu:10443/asview
          - name: 'NCAR k8s JupyterHub'
            url: https://jupyter.k8s.ucar.edu/
          - name: Rancher
            url: https://rancher.k8s.ucar.edu/
          - name: 'NCAR HPC JupyterHub'
            url: https://jupyterhub.hpc.ucar.edu/
          - name: Request VM
            url: https://ithelp.ucar.edu/servicedesk/customer/portal/2/create/17
          - name: '2i2c AWS JupyterHub'
            url: https://ncar-cisl.2i2c.cloud/hub/login
        - name: CISL Home
          url: https://www2.cisl.ucar.edu/
        - name: New Request
          url: https://jira.ucar.edu/secure/CreateIssueDetails!init.jspa?pid=18470&issuetype=10903&customfield_10281=CCPP-108
        - name: Report issue
          url: https://jira.ucar.edu/secure/CreateIssueDetails!init.jspa?pid=18470&issuetype=10905
      page_layouts:
        index: page-banner.html
    html_sidebars:
      index: []