site_name: CCPP Documentation
site_url: https://jira.ucar.edu/secure/RapidBoard.jspa?rapidView=220&projectKey=CCPP
site_description: Documentation for the CISL Cloud Pilot Program
repo_url: https://github.com/NCAR/cisl-cloud/tree/main/docs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Services: services.md
  - How-To: 
      - "Agile Interaction": how-to/agile.md
      - "Documentation Site Build": how-to/build-docs.md
theme: 
  name: readthedocs
  logo: 'images/ncar-cisl-white.png'
extra_css:
  - "css/extra.css"
extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.js
  - js/extra.js
  