replicaCount: 1

webapp:
  name: cloud-docs
  group: cloud-docs
  path: /
  tls:
    fqdn: cloud-docs.k8s.ucar.edu
    secretName: incommon-cert-cloud-docs
  container: 
    imagePullPolicy: Always
    port: 80
    memory: 1G
    cpu: 2    
    image: hub.k8s.ucar.edu/docker/cislcloudpilot/docs:2024-03-13.23
