# This workflow builds docker images and pushes them to a Docker Hub Repository

name: Deploy base-notebook

on:
  push:
    paths:
      - configs/jupyter/base-notebook/**
    
jobs:
  deploy-docker-base-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ncote/cisl-cloud-base

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: configs/jupyter/base-notebook/Dockerfile
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}