# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: Build Documentation container

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the docs/_build/html/ path
on:
  push:
    paths:
      - docs/_build/html/**

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  build-docs-image:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: ubuntu-latest
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the repo
        uses: actions/checkout@v3
      # Step 2 is to login to docker hub so the image can be pushed
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        # GitHub secrets are used to provide login information to docker hub
        with:
          username: ${{ secrets.CCP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CCP_DOCKERHUB_TOKEN  }}
      # Pull relevant metadata out of the docker image used
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cislcloudpilot/docs
      # Build and push the docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Provide the current directory as build context 
          context: .
          # Specify where the Dockerfile is located in relation to the repo base path
          file: docs/Dockerfile
          # Enable the push to docker hub
          push: true
          # Provide the tags to apply to the image, this example uses the latest image tag 
          tags: |
            cislcloudpilot/docs:latest
            cislcloudpilot/docs:Aug.14.23
          # Apply labels as defined in the Docker image metadata
          labels: ${{ steps.meta.outputs.labels }}