name: Cloud Docs CI/CD 

on:
  push:
    branches:
      - docs

jobs:
  build-docs:
    runs-on: self-hosted
    steps:
      # Step 1 is to checkout the github repo
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: docs
      - name: Build book HTML
        run: |
          jupyter-book build /home/podman/actions-runner/_work/cisl-cloud/cisl-cloud/.
      - name: Push _build/html to gh-pages
        run: |
          chown -R $(whoami):$(whoami) .
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.NC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
          ls -lrt
          ghp-import -n -p -f /home/podman/actions-runner/_work/cisl-cloud/cisl-cloud/_build/html
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build Podman image
        run: |
          podman build -f docs.Dockerfile -t hub.k8s.ucar.edu/cislcloudpilot/docs:${{ steps.date.outputs.date }} /home/podman/actions-runner/_work/cisl-cloud/cisl-cloud/.
      - name: Login to Harbor
        run: podman login hub.k8s.ucar.edu -u robot-cislcloudpilot+cislcloudpilot -p ${{ secrets.HARBOR_LOGIN  }}
      - name: Push Podman image to Harbor
        run: |
          podman push hub.k8s.ucar.edu/cislcloudpilot/docs:${{ steps.date.outputs.date }}
  update-helm:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: ubuntu-latest
    # Set the steps to take in order
    needs: build-docs
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the main repo
        uses: actions/checkout@v4
        with:
          ref: dev
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Update Helm values.yaml
        run: | 
          sed -i '15d' cluster/helm-charts/cloud-docs/values.yaml
          echo "    image: hub.k8s.ucar.edu/cislcloudpilot/docs:${{ steps.date.outputs.date }}" >> cluster/helm-charts/cloud-docs/values.yaml
      - name: Update Helm Chart.yaml
        run: | 
          sed -i '24d' cluster/helm-charts/cloud-docs/Chart.yaml
          echo "appVersion: '${{ steps.date.outputs.date }}'" >> cluster/helm-charts/cloud-docs/Chart.yaml
      - name: Run python script to update version by 1
        run: python cluster/helm-charts/cloud-docs/update_ver.py
      - name: Commit changes to dev branch
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git commit -a -m "Update Helm chart via GH Actions"
          git push
      - name: Create pull request to merge dev Helm chart in to main
        run: gh pr create -B main -H dev --title 'Merge documentation Helm chart CICD update from dev into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}