name: Cloud Docs CI/CD 

on:
  push:
    paths:
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1 is to checkout the github repo
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          sudo apt-get install python3-pip
          pip install ghp-import
          pip install jupyter-book
          PATH="${PATH}:${HOME}/.local/bin"
      - name: Build book HTML
        run: |
          jupyter-book build .
      - name: Push _build/html to gh-pages
        run: |
          sudo chown -R $(whoami):$(whoami) .
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.NC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
          ls -lrt
          ghp-import -n -p -f _build/html