# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: JHub RDP Build & Push

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the images/jupyter/base-notebook/ path
on:
  push:
    paths:
      - images/jupyter/rdp-notebook/**
    branches:
      - main

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  podman-build-push-rdp-notebook:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: self-hosted
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Containerfile
      - name: Check out the repo
        uses: actions/checkout@v4
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build Podman image
        run: |
          podman build -f images/jupyter/rdp-notebook/Containerfile -t hub.k8s.ucar.edu/cislcloudpilot/cisl-cloud-rdp:${{ steps.date.outputs.date }} images/jupyter/rdp-notebook/. --no-cache --format=docker
      - name: Login to Harbor
        run: podman login hub.k8s.ucar.edu -u robot-cislcloudpilot+cislcloudpilot -p ${{ secrets.HARBOR_LOGIN  }}
      - name: Push Podman image to Harbor
        run: |
          podman push hub.k8s.ucar.edu/cislcloudpilot/cisl-cloud-rdp:${{ steps.date.outputs.date }}