# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: PyTorch Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the configs/jupyter/base-notebook/ path
on:
  push:
    paths:
      - configs/jupyter/gpu-pyt-notebook/**
    branches:
      - dev

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  deploy-docker-gpu-pyt-notebook:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: self-hosted
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the repo
        uses: actions/checkout@v3
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build Podman image
        run: |
          podman build -f configs/jupyter/gpu-pyt-notebook/Dockerfile -t hub.k8s.ucar.edu/cislcloudpilot/cisl-cloud-gpu-pyt:${{ steps.date.outputs.date }} configs/jupyter/gpu-pyt-notebook/. --no-cache --format=docker
      - name: Create pull request to merge dev in to main
        run: gh pr create -B main -H dev --title 'Test build successful. Merge tensorflow notebook update from dev into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}