# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: Tensorflow Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the configs/jupyter/base-notebook/ path
on:
  push:
    paths:
      - configs/jupyter/gpu-tf-notebook/**
    branches:
      - dev

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  deploy-docker-gpu-tf-notebook:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: self-hosted
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the repo
        uses: actions/checkout@v3
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Install Podman
        run: |
          sudo apt-get remove -y golang-github-containers-image \
          && sudo mkdir -p /etc/apt/keyrings \
          && curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/Release.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null \
          && echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
            https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null \
          && sudo apt-get update -y \
          && sudo apt-get install -y podman skopeo
      - name: Build Podman image
        run: |
          podman build -f configs/jupyter/gpu-tf-notebook/Dockerfile -t cislcloudpilot/cisl-cloud-gpu-tf:${{ steps.date.outputs.date }} configs/jupyter/gpu-tf-notebook/. --format=docker