# This workflow builds docker images and pushes them to a Docker Hub Repository
# This workflow is specific to the base-notebook directory and image
# Set the workflow name
name: Tensorflow Build Test

# Define the trigger that starts the action
# For this workflow the trigger is on a push that changes anything in the configs/jupyter/base-notebook/ path
on:
  push:
    paths:
      - configs/jupyter/gpu-tf-notebook/**
    branches:
      - dev

# Define the actions that are going to take place as part of this workflow    
jobs:
  # Name the job(s)
  deploy-docker-gpu-tf-notebook:
    # Define where the job should run in this case it will be run on the latest ubuntu image
    runs-on: self-hosted
    # Set the steps to take in order
    steps:
      # Step 1 is to checkout the github repo used to build the Dockerfile
      - name: Check out the repo
        uses: actions/checkout@v3
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      # Build and push the docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Provide the current directory as build context 
          context: configs/jupyter/gpu-tf-notebook/.
          # Specify where the Dockerfile is located in relation to the repo base path
          file: configs/jupyter/gpu-tf-notebook/Dockerfile
          # Enable the push to docker hub
          push: false
          # Provide the tags to apply to the image, this example uses the latest image tag 
          tags: |
            cislcloudpilot/cisl-cloud-gpu-tf:${{ steps.date.outputs.date }}